gnome-terminal --tab --title="1" --command="bash -c ' GK=true TEAM=ts_team X=-52 Y=0 node ./app.js > ./logs/1.log 2> ./logs/1-error.log'" 
gnome-terminal --tab --title="2" --command="bash -c ' TEAM=ts_team X=-36 Y=-13 node ./app.js > ./logs/2.log 2> ./logs/2-error.log'" 
gnome-terminal --tab --title="3" --command="bash -c ' TEAM=ts_team X=-36 Y=0 node ./app.js > ./logs/3.log 2> ./logs/3-error.log'" 
gnome-terminal --tab --title="4" --command="bash -c ' TEAM=ts_team X=-36 Y=13 node ./app.js > ./logs/4.log 2> ./logs/4-error.log'"
gnome-terminal --tab --title="5" --command="bash -c ' TEAM=ts_team X=-26 Y=-26 node ./app.js > ./logs/5.log 2> ./logs/5-error.log'"  
gnome-terminal --tab --title="6" --command="bash -c ' TEAM=ts_team X=-26 Y=26 node ./app.js > ./logs/6.log 2> ./logs/6-error.log'"  
gnome-terminal --tab --title="7" --command="bash -c ' TEAM=ts_team X=-26 Y=-10 node ./app.js > ./logs/7.log 2> ./logs/7-error.log'"  
gnome-terminal --tab --title="8" --command="bash -c ' TEAM=ts_team X=-26 Y=10 node ./app.js > ./logs/8.log 2> ./logs/8-error.log'" 
gnome-terminal --tab --title="9" --command="bash -c ' TEAM=ts_team X=-15 Y=0 node ./app.js > ./logs/9.log 2> ./logs/9-error.log'"
gnome-terminal --tab --title="10" --command="bash -c ' TEAM=ts_team X=-7 Y=-7 node ./app.js > ./logs/10.log 2> ./logs/10-error.log'"  
gnome-terminal --tab --title="11" --command="bash -c ' TEAM=ts_team X=-7 Y=7 node ./app.js > ./logs/11.log 2> ./logs/11-error.log'" 