gnome-terminal --tab --title="1" --command="bash -c ' GK=true TEAM=losers_team X=-52 Y=0 node ./app.js > ./logs/2_1.log 2> ./logs/2_1-error.log'" 
gnome-terminal --tab --title="2" --command="bash -c ' TEAM=losers_team X=-36 Y=-13 node ./app.js > ./logs/2_2.log 2> ./logs/2_2-error.log'" 
gnome-terminal --tab --title="3" --command="bash -c ' TEAM=losers_team X=-36 Y=0 node ./app.js > ./logs/2_3.log 2> ./logs/2_3-error.log'" 
gnome-terminal --tab --title="4" --command="bash -c ' TEAM=losers_team X=-36 Y=13 node ./app.js > ./logs/2_4.log 2> ./logs/2_4-error.log'"
gnome-terminal --tab --title="5" --command="bash -c ' TEAM=losers_team X=-26 Y=-26 node ./app.js > ./logs/2_5.log 2> ./logs/2_5-error.log'"  
gnome-terminal --tab --title="6" --command="bash -c ' TEAM=losers_team X=-26 Y=26 node ./app.js > ./logs/2_6.log 2> ./logs/2_6-error.log'"  
gnome-terminal --tab --title="7" --command="bash -c ' TEAM=losers_team X=-26 Y=-10 node ./app.js > ./logs/2_7.log 2> ./logs/2_7-error.log'"  
gnome-terminal --tab --title="8" --command="bash -c ' TEAM=losers_team X=-26 Y=10 node ./app.js > ./logs/2_8.log 2> ./logs/2_8-error.log'" 
gnome-terminal --tab --title="9" --command="bash -c ' TEAM=losers_team X=-15 Y=0 node ./app.js > ./logs/2_9.log 2> ./logs/2_9-error.log'"
gnome-terminal --tab --title="10" --command="bash -c ' TEAM=losers_team X=-7 Y=-7 node ./app.js > ./logs/2_10.log 2> ./logs/2_10-error.log'"  
gnome-terminal --tab --title="11" --command="bash -c ' TEAM=losers_team X=-7 Y=7 node ./app.js > ./logs/2_11.log 2> ./logs/2_11-error.log'" 